name: Tests
on: [workflow_call]
permissions: {}

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.3
        with:
          command: test
          args: --all -- --nocapture
      - uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.3
        with:
          command: test
          args: --all --features pretend_to_be_macos -- --nocapture

  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.3
        with:
          command: test
          args: --all --lib -- --nocapture

  test-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.3
        with:
          command: test
          args: --all --lib -- --nocapture

  test-ffi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: true
      - uses: Swatinem/rust-cache@b8a6852b4f997182bdea832df3f9e153038b5191 # v2.6.0
      - name: Build libtelio
        run: python3 ci/build_libtelio.py build linux x86_64
      - name: Test FFI
        run: |
          cd ./ffi/tests
          mkdir build
          cd build
          cmake ..
          make
          sudo ./test_panic

  test-replacement-script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Test replacement script
        run: python3 ci/test_replace_string.py

  test-build-version-replacement-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: true
      - uses: Swatinem/rust-cache@b8a6852b4f997182bdea832df3f9e153038b5191 # v2.6.0
        with:
          key: x86-linux
      - name: Build libtelio
        run: python3 ci/build_libtelio.py build linux x86_64
      - name: Replace and Test version
        run: |
          BRANCH=${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}
          SHA=${GITHUB_SHA:-$(git rev-parse HEAD)}
          DATE=$(git show ${SHA} -s --date=format:'%Y%m%d/%H%M' --format=%cd)
          BUILD_TAG="${BRANCH}+${DATE}+${SHA:0:8}"
          ./ci/insert_libtelio_version.py -n ${BUILD_TAG} -p ./dist/linux
          ./dist/linux/release/x86_64/tcli
          echo "Build tag ${BUILD_TAG}"
          head -n 1 tcli.log | grep -a "${BUILD_TAG}"

  test-build-version-replacement-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: true
      - uses: Swatinem/rust-cache@b8a6852b4f997182bdea832df3f9e153038b5191 # v2.6.0
        with:
          key: x86-macos
      - name: Build libtelio
        run: python3 ci/build_libtelio.py build macos x86_64
      - name: Replace and Test version
        run: |
          BRANCH=${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}
          SHA=${GITHUB_SHA:-$(git rev-parse HEAD)}
          DATE=$(git show ${SHA} -s --date=format:'%Y%m%d/%H%M' --format=%cd)
          BUILD_TAG="${BRANCH}+${DATE}+${SHA:0:8}"
          ./ci/insert_libtelio_version.py -n ${BUILD_TAG} -p ./dist/darwin/macos
          ./dist/darwin/macos/release/x86_64/tcli
          echo "Build tag ${BUILD_TAG}"
          head -n 1 tcli.log | grep -a "${BUILD_TAG}"
